[versions]
com-fasterxml-jackson-datatype-jackson-datatype-jsr310 = "2.21.0"
commons-io-commons-io = "2.21.0"
io-github-stevenjwest-paralleliterativedeconvolution = "1.13"
net-imagej-ij = "1.54p"
org-apache-commons-commons-text = "1.15.0"
org-apache-velocity-velocity-engine-core = "2.4.1"
org-projectlombok-lombok = "1.18.42"
org-yaml-snakeyaml = "2.5"
palantir-java-format = "2.87.0"
parallelcolt = "0.11.4"
commons-math3 = "3.5"
spring-boot = "3.5.10"
springDependencyManagement = "1.1.7"
spotless = "8.2.1"
jtransforms = "3.2"
httpclient5 = "5.6"
bunwarpj = "2.6.12"
turboreg = "2.0.1-SNAPSHOT"
kotlin = "2.3.10"
ktfmt = "0.61"
httpcore5 = "5.4.1"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

[libraries]
com-fasterxml-jackson-datatype-jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "com-fasterxml-jackson-datatype-jackson-datatype-jsr310" }
commons-io-commons-io = { module = "commons-io:commons-io", version.ref = "commons-io-commons-io" }
io-github-stevenjwest-paralleliterativedeconvolution = { module = "io.github.stevenjwest:ParallelIterativeDeconvolution", version.ref = "io-github-stevenjwest-paralleliterativedeconvolution" }
net-imagej-ij = { module = "net.imagej:ij", version.ref = "net-imagej-ij" }
org-apache-commons-commons-text = { module = "org.apache.commons:commons-text", version.ref = "org-apache-commons-commons-text" }
org-apache-velocity-velocity-engine-core = { module = "org.apache.velocity:velocity-engine-core", version.ref = "org-apache-velocity-velocity-engine-core" }
org-projectlombok-lombok = { module = "org.projectlombok:lombok", version.ref = "org-projectlombok-lombok" }
org-springframework-boot-spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
org-springframework-boot-spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
org-springframework-boot-spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
org-yaml-snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "org-yaml-snakeyaml" }
com-github-wendykierp-jtransforms = { module = "com.github.wendykierp:JTransforms", version.ref = "jtransforms" }
net-sourceforge-parallelcolt = { module = "net.sourceforge.parallelcolt:parallelcolt", version.ref = "parallelcolt" }
org-apache-commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
org-apache-httpcomponents-client5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5" }
sc-fiji-bunwarpj = { module = "sc.fiji:bUnwarpJ_", version.ref = "bunwarpj" }
sc-fiji-turboreg = { module = "sc.fiji:TurboReg_", version.ref = "turboreg" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
org-apache-httpcomponents-core5-httpcore5 = { module = "org.apache.httpcomponents.core5:httpcore5", version.ref = "httpcore5" }